Codigo/QueroTransporteSolucao/QueroTransporteWeb/Controllers/FrotaController.cs
using Domain.Interfaces.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QueroTransporte.Model;

namespace QueroTransporteWeb.Controllers
{
    [Authorize]
    public class FrotaController : Controller
    {
        private readonly IFrotaService FrotaService;
        public FrotaController(IFrotaService frotaService)
        {
            FrotaService = frotaService;
        }
        // GET: Frota
        public IActionResult Index()
        {
            return View(FrotaService.FrotaUnityOfWork.FrotaRepository.ObterTodos());
        }

        // GET: Frota/Details/5
        public IActionResult Details(int id)
        {
            return View(FrotaService.FrotaUnityOfWork.FrotaRepository.ObterPorId(id));
        }

        // GET: Frota/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Frota/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FrotaModel frota)
        {
            try
            {
                if (ModelState.IsValid && FrotaService.FrotaUnityOfWork.FrotaRepository.Inserir(frota))
                    return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(frota);
            }
            return View(frota);
        }

        // GET: Frota/Edit/5
        public IActionResult Edit(int id)
        {
            return View(FrotaService.FrotaUnityOfWork.FrotaRepository.ObterPorId(id));
        }

        // POST: Frota/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Frota/Delete/5
        public IActionResult Delete(int id) => View(FrotaService.FrotaUnityOfWork.FrotaRepository.ObterPorId(id));

        // POST: Frota/Delete/5
        public IActionResult Remove(int id)
        {
            try
            {
                if (FrotaService.FrotaUnityOfWork.FrotaRepository.Remover(id))
                    return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index), new { msg = "Erro" });
        }
    }
}

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Controllers/HistoricoController.cs
using Domain.Interfaces.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace QueroTransporteWeb.Controllers
{
    [Authorize]
    public class HistoricoController : Controller
    {
        private readonly ITransacaoService TransacaoService;
        private readonly IViagemService ViagemService;
        private readonly ISolicitacaoService SolicitacaoService;
        public HistoricoController(ITransacaoService gerenciadorTransacao, IViagemService gerenciadorViagem, ISolicitacaoService gerenciadorSolicitacao)
        {
            SolicitacaoService = gerenciadorSolicitacao;
            ViagemService = gerenciadorViagem;
            TransacaoService = gerenciadorTransacao;
        }
        public IActionResult HistoricoTransacoes()
        {
            ViewBag.deferidas = TransacaoService.TransacaoUnityOfWork.TransacaoRepository.ObterTodasDeferidas(true).Count();
            ViewBag.indeferidas = TransacaoService.TransacaoUnityOfWork.TransacaoRepository.ObterTodasDeferidas(false).Count();
            return View();
        }

        public IActionResult HistoricoViagens()
        {
            ViewBag.realizada = ViagemService.ViagemUnityOfWork.ViagemRepository.ObterTodosAbertos(true).Count();
            ViewBag.naoRealizada = ViagemService.ViagemUnityOfWork.ViagemRepository.ObterTodosAbertos(false).Count();
            return View();
        }

        public IActionResult HistoricoSolicitacoes()
        {
            ViewBag.atendidas = SolicitacaoService.SolicitacaoUnityOfWork.SolicitacaoRepository.ObterTodosAtendidas(true).Count();
            ViewBag.naoAtendidas = SolicitacaoService.SolicitacaoUnityOfWork.SolicitacaoRepository.ObterTodosAtendidas(false).Count();
            return View();
        }
    }
}

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Controllers/UsuarioController.cs
using Domain.Interfaces.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using QueroTransporte.Model;
using QueroTransporteWeb.Resources.Methods;
using System.Linq;

namespace QueroTransporteWeb.Controllers
{
    [Authorize]
    public class UsuarioController : Controller
    {
        private readonly IUsuarioService UsuarioService;

        public UsuarioController(IUsuarioService gerenciadorUsuario)
        {
            UsuarioService = gerenciadorUsuario;
        }

        /// <summary>
        /// método da view padrão do controlador
        /// </summary>
        /// <returns>Todos os usuarios que não são motoristas para o view que lista eles</returns>
        // GET: Usuario
        public ActionResult Index() => View(UsuarioService.UsuarioUnityOfWork.UsuarioRepository.ObterTodos().Where(u => !u.Tipo.Equals("MOTORISTA")));

        /// <summary>
        /// detalha o dados do usuario
        /// </summary>
        /// <param name="id">serve para buscar um usuario, para posteriormente retorna-lo na view</param>
        /// <returns>retorna na view o usuario</returns>
        // GET: Usuario/Details/5
        public ActionResult Details(int id) => View(UsuarioService.UsuarioUnityOfWork.UsuarioRepository.ObterPorId(id));

        /// <summary>
        /// Para assim que a funcao criar um usuario é chamada
        /// </summary>
        /// <returns></returns>
        // GET: Usuario/Create
        public ActionResult Create()
        {
            ViewBag.Tipos = new SelectList(UsuarioService.UsuarioUnityOfWork.UsuarioRepository.GetTipos(), "string");
            return View();
        }

        /// <summary>
        /// Serve para a partir de um formulario receber os dados e criar um usuario 
        /// </summary>
        /// <param name="usuarioModel">Usuario criado a partir do formulario</param>
        /// <returns></returns>
        // POST: Usuario/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UsuarioModel usuarioModel)
        {
            if (ModelState.IsValid)
            {
                usuarioModel.Cpf = MethodsUtils.RemoverCaracteresEspeciais(usuarioModel.Cpf);
                usuarioModel.Telefone = MethodsUtils.RemoverCaracteresEspeciais(usuarioModel.Telefone);
                if (UsuarioService.UsuarioUnityOfWork.UsuarioRepository.Inserir(usuarioModel))
                    return RedirectToAction(nameof(Index));
            }
            return View(usuarioModel);
        }

        /// <summary>
        /// Assim que é chamada a funcao para editar um determinado usuario
        /// </summary>
        /// <param name="id">id do usuario selecionado para edicao</param>
        /// <returns></returns>
        // GET: Usuario/Edit/5
        public ActionResult Edit(int id)
        {
            UsuarioModel user = new UsuarioModel();
            user = UsuarioService.UsuarioUnityOfWork.UsuarioRepository.ObterPorId(id);
            ViewBag.Tipos = new SelectList(UsuarioService.UsuarioUnityOfWork.UsuarioRepository.GetTipos(), "string");
            return View(user);
        }

        /// <summary>
        /// Edita um usuario a partir do formulario 
        /// </summary>
        /// <param name="usuarioModel">Usuario criado a partir do formulario</param>
        /// <returns></returns>
        // POST: Usuario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UsuarioModel usuarioModel)
        {
            if (ModelState.IsValid)
            {
                if (UsuarioService.UsuarioUnityOfWork.UsuarioRepository.Editar(usuarioModel))
                    return RedirectToAction(nameof(Index));
            }
            return View(usuarioModel);
        }

        /// <summary>
        /// ASsim que é chamada o botao deletar um usuario
        /// </summary>
        /// <param name="id">id do usuario selecionado para exclusao</param>
        /// <returns></returns>
        // GET: Usuario/Delete/5
        public ActionResult Delete(int id) => View(UsuarioService.UsuarioUnityOfWork.UsuarioRepository.ObterPorId(id));

        /// <summary>
        /// Serve para excluir um usuario
        /// </summary>
        /// <param name="id">id do usario a ser deletado</param>
        /// <param name="collection">Objeto da interface controller</param>
        /// <returns></returns>
        // POST: Usuario/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            UsuarioService.UsuarioUnityOfWork.UsuarioRepository.Remover(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Controllers/ViagemController.cs
using Domain.Interfaces.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Model.ViewModel;
using QueroTransporte.Model;
using System.Collections.Generic;

namespace QueroTransporteWeb.Controllers
{
    [Authorize]
    public class ViagemController : Controller
    {
        private readonly IViagemService ViagemService;
        private readonly IRotaService RotaService;
        private readonly IVeiculoService VeiculoService;
        public ViagemController(IViagemService gerenciador, IRotaService gerenciadorRota, IVeiculoService gerenciadorVeiculo)
        {
            ViagemService = gerenciador;
            RotaService = gerenciadorRota;
            VeiculoService = gerenciadorVeiculo;
        }
        // GET: ManterViagem
        public IActionResult Index()
        {
            var listViewModels = new List<ViagemRotaViewModel>();
            foreach (var viagem in ViagemService.ViagemUnityOfWork.ViagemRepository.ObterTodos())
            {
                var rota = RotaService.RotaUnityOfWork.RotaRepository.ObterPorId(viagem.IdRota);
                var veiculo = VeiculoService.VeiculoUnityOfWork.VeiculoRepository.ObterPorId(viagem.IdVeiculo);

                listViewModels.Add(new ViagemRotaViewModel()
                {
                    Rota = rota,
                    Veiculo = veiculo,
                    Viagem = viagem
                });
            }

            return View(listViewModels);
        }

        // GET: ManterViagem/Details/5
        public IActionResult Details(int id)
        {
            var viagem = ViagemService.ViagemUnityOfWork.ViagemRepository.ObterPorId(id);
            ViewBag.rota = RotaService.RotaUnityOfWork.RotaRepository.ObterPorId(viagem.IdRota);
            ViewBag.placa = VeiculoService.VeiculoUnityOfWork.VeiculoRepository.ObterPorId(viagem.IdVeiculo);
            return View(viagem);
        }

        // GET: ManterViagem/Create
        public IActionResult Create()
        {
            ViewBag.rotas = new SelectList(RotaService.RotaUnityOfWork.RotaRepository.ObterDetalhesRota(), "Id", "DetalhesRota");
            ViewBag.placas = new SelectList(VeiculoService.VeiculoUnityOfWork.VeiculoRepository.ObterTodos(), "Id", "Placa");
            return View();
        }

        // POST: ManterViagem/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ViagemModel viagemModel)
        {
            try
            {
                if (ViagemService.ViagemUnityOfWork.ViagemRepository.Inserir(viagemModel))
                    return RedirectToAction(nameof(Index));

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: ManterViagem/Edit/5
        public IActionResult Edit(int id)
        {
            var viagem = ViagemService.ViagemUnityOfWork.ViagemRepository.ObterPorId(id);
            var rotas = RotaService.RotaUnityOfWork.RotaRepository.ObterTodos();
            ViewBag.rotas = new SelectList(RotaService.RotaUnityOfWork.RotaRepository.ObterDetalhesRota(), "Id", "DetalhesRota");
            ViewBag.placas = new SelectList(VeiculoService.VeiculoUnityOfWork.VeiculoRepository.ObterTodos(), "Id", "Placa");
            return View(viagem);
        }

        // POST: ManterViagem/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, ViagemModel viagemModel)
        {
            try
            {
                if (ViagemService.ViagemUnityOfWork.ViagemRepository.Editar(viagemModel))
                    return RedirectToAction(nameof(Index));

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: ManterViagem/Delete/5
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var viagem = ViagemService.ViagemUnityOfWork.ViagemRepository.ObterPorId(id);
            ViewBag.rota = RotaService.RotaUnityOfWork.RotaRepository.ObterPorId(viagem.IdRota);
            ViewBag.placa = VeiculoService.VeiculoUnityOfWork.VeiculoRepository.ObterPorId(viagem.IdVeiculo);
            return View(viagem);
        }

        // POST: ManterViagem/Delete/5
        public IActionResult Remove(int id)
        {
            try
            {
                if (ViagemService.ViagemUnityOfWork.ViagemRepository.Remover(id))
                    return RedirectToAction(nameof(Index));
                else
                    return RedirectToAction(nameof(Delete));
            }
            catch
            {
                return RedirectToAction(nameof(Delete));
            }
        }
    }
}

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="~/images/queroTransporteLogo.png" type="image/ico" />
    <title>@ViewData["Title"] - QueroTransporteWeb</title>


    <link rel="stylesheet" type="text/css" href="~/css/estiloComprarCreditos.css">
    <!-- Bootstrap -->
    <link href="~/template/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/template/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/template/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="~/template/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="~/template/build/css/custom.min.css" rel="stylesheet">
</head>

@if (!User.Identity.IsAuthenticated)
{
    <body class="login">
        @RenderBody()
        @RenderSection("Scripts", required: false)
    </body>
}
else
{
    <body class="nav-md">
        <div class="container body">
            <div class="main_container">
                <partial name="_MenuPartial" />
                <partial name="_TopBarPartial" />
                <div class="right_col" role="main">
                    <div class="row">
                        <div class="x_panel">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
            <footer>
                <div class="pull-right">
                    Quero Transporte 2020
                </div>
                <div class="clearfix"></div>
            </footer>
        </div>


        <!-- jQuery -->
        <script src="~/template/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="~/template/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="~/template/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="~/template/vendors/nprogress/nprogress.js"></script>
        <!-- iCheck -->
        <script src="~/template/vendors/iCheck/icheck.min.js"></script>
        <!-- validator -->
        <script src="~/template/vendors/validator/validator.js"></script>
        <!-- jquery.inputmask -->
        <script src="~/template/vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>

        <!-- Custom Theme Scripts -->
        <script src="~/template/build/js/custom.min.js"></script>

        @RenderSection("Scripts", required: false)
    </body>
}
</html>

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Views/Shared/_MenuPartial.cshtml
@using System.Security.Claims;

@{
    ViewData["Title"] = "_MenuPartial";

    var claimsIdentity = User.Identity as ClaimsIdentity;
    string nome = "";
    string role = "";

    if (claimsIdentity != null)
    {
        nome = claimsIdentity.Claims.Where(s => s.Type == ClaimTypes.NameIdentifier).Select(s => s.Value).FirstOrDefault();
        role = claimsIdentity.Claims.Where(s => s.Type == ClaimTypes.Role).Select(s => s.Value).FirstOrDefault();
    }
}

<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a asp-controller="Home" asp-action="Index" class="site_title"><i class="fa fa-car"></i> <span>Quero Transporte</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="https://99181-282044-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2016/05/icon-user-default.png" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Bem Vindo,</span>
                <h2>@nome</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->
        <br>

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                    <li>
                        <a asp-controller="Home" asp-action="Index"><i class="fa fa-bar-chart"></i> Dashboard </a>
                    </li>
                    @if (User.IsInRole("MOTORISTA"))
                    {

                    }
                    else if (User.IsInRole("ADMIN"))
                    {
                        <li>
                            <a asp-controller="Frota" asp-action="Index"><i class="fa fa-car"></i> Frotas </a>
                        </li>
                        <!--
                        <li>
                            <a asp-controller="Rota" asp-action="Index"><i class="fa fa-road"></i> Rotas </a>
                        </li>
                        <li>
                            <a asp-controller="Viagem" asp-action="Index"><i class="fa fa-road"></i> Viagem </a>
                        </li>
                        -->
                        <li>
                            <a asp-controller="Veiculo" asp-action="Index"><i class="fa fa-car"></i> Veiculos </a>
                        </li>
                        <li>
                            <a asp-controller="Usuario" asp-action="Index"><i class="fa fa-user"></i> Usuarios </a>
                        </li>
                        <li>
                            <a asp-controller="Motorista" asp-action="Index"><i class="fa fa-edit"></i> Motoristas </a>
                        </li>
                        <li>
                            <a asp-controller="ConsumivelVeicular" asp-action="Index"><i class="fa fa-edit"></i> Consumíveis Veículares </a>
                        </li>
                        @*<li>
                                <a asp-controller="Historico" asp-action="HistoricoTransacoes"><i class="fa fa-history"></i> Gráfico de Transacoes </a>
                            </li>
                        <li>
                            <a asp-controller="Historico" asp-action="HistoricoViagens"><i class="fa fa-history"></i> Gráfico de Viagens </a>
                        </li>
                            <li>
                                <a asp-controller="Historico" asp-action="HistoricoSolicitacoes"><i class="fa fa-history"></i> Gráfico de Solicitações </a>
                            </li>
                            <li>
                                <a asp-controller="ConsumivelVeicular" asp-action="Reports"><i class="fa fa-history"></i> Gráfico de Consumiveis </a>
                            </li>*@
                    }
                    @*<li>
                            <a asp-controller="ComprarCreditos" asp-action="Index"><i class="fa fa-shopping-cart"></i> Comprar Creditos </a>
                        </li>
                        <li>
                                <a asp-controller="Solicitacao" asp-action="Index"><i class="fa fa-shopping-cart"></i> Solicitar Viagem </a>
                            </li>
                            <li>
                                <a asp-controller="PagarPassagem" asp-action="Index"><i class="fa fa-edit"></i> Pagar Passagem </a>
                            </li>*@
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->
    </div>
</div>

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Views/Shared/_TopBarPartial.cshtml
@using System.Security.Claims;

@{
    ViewData["Title"] = "_TopBarPartial";

    var claimsIdentity = User.Identity as ClaimsIdentity;
    string nome = "";
    int idUsuario = 0;

    if (claimsIdentity != null)
    {
        idUsuario = int.Parse(claimsIdentity.Claims.Where(s => s.Type == ClaimTypes.SerialNumber).Select(s => s.Value).FirstOrDefault());
        nome = claimsIdentity.Claims.Where(s => s.Type == ClaimTypes.NameIdentifier).Select(s => s.Value).FirstOrDefault();
    }
}

<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="https://99181-282044-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2016/05/icon-user-default.png" alt="">@nome
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <!--
    <li><a href="@Url.Action("Editar", "Usuario", new { id = idUsuario })"> Meus Dados </a></li>
    <li>
        <a href="javascript:;">
            <span class="badge bg-red pull-right">50%</span>
            <span>Configurações</span>
        </a>
    </li>
        -->
                        <li><a href="@Url.Action("Logout", "Login")"><i class="fa fa-sign-out pull-right"></i> Sair </a></li>
                    </ul>
                </li>

                <!--
    <li role="presentation" class="dropdown">
        <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">1</span>
        </a>
        <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
                <a>
                    <span class="image"><img src="https://99181-282044-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2016/05/icon-user-default.png" alt="Profile Image"></span>
                    <span>
                        <span>Gabriel Santana</span>
                        <span class="time">3 mins ago</span>
                    </span>
                    <span class="message">
                        Exemplo de notificação.
                    </span>
                </a>
            </li>
            <li>
                <div class="text-center">
                    <a>
                        <strong>Ver todos alertas</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>
            </li>
        </ul>
    </li>
        -->
            </ul>
        </nav>
    </div>
</div>