Codigo/QueroTransporteSolucao/QueroTransporteWeb/Controllers/ConsumivelVeicularController.cs
using Domain.Interfaces.Services;
using Domain.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Model.ViewModel;
using QueroTransporte.Model;
using System.Collections.Generic;
using System.Linq;

namespace QueroTransporte.QueroTransporteWeb
{
    [Authorize]
    public class ConsumivelVeicularController : Controller
    {
        private readonly IConsumivelService ConsumivelService;
        private readonly IVeiculoService VeiculoService;

        public ConsumivelVeicularController(IConsumivelService consumivelService, IVeiculoService veiculoService)
        {
            ConsumivelService = consumivelService;
            VeiculoService = veiculoService;
        }

        public IActionResult Index()
        {
            var consVeic = new List<ConsumivelVeiculoViewModel>();
            foreach (var c in ConsumivelService.ConsumivelUnityOfWork.ConsumivelVeicularRepository.ObterTodos())
                consVeic.Add(new ConsumivelVeiculoViewModel { ConsumivelVeicular = c, Veiculo = VeiculoService.VeiculoUnityOfWork.VeiculoRepository.ObterPorId(c.IdVeiculo) });

            return View(consVeic);
        }

        public IActionResult Create()
        {
            ViewBag.Consumiveis = new SelectList(ConsumivelService.ConsumivelUnityOfWork.ConsumivelVeicularRepository.ObterTodos(), "Id");
            ViewBag.Veiculos = new SelectList(VeiculoService.VeiculoUnityOfWork.VeiculoRepository.ObterTodos(), "Id", "Placa");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ConsumivelVeicularModel consumivelveicularModel)
        {
            if (ModelState.IsValid)
            {
                if (VeiculoService.VeiculoUnityOfWork.VeiculoRepository.ObterPorId(consumivelveicularModel.IdVeiculo) != null)
                {
                    if (ConsumivelService.ConsumivelUnityOfWork.ConsumivelVeicularRepository.Inserir(consumivelveicularModel))
                        return RedirectToAction(nameof(Index));
                }
            }
            return View(consumivelveicularModel);
        }

        public IActionResult Edit(int id) => View(ConsumivelService.ConsumivelUnityOfWork.ConsumivelVeicularRepository.ObterPorId(id));

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, ConsumivelVeicularModel consumivelveicularModel)
        {
            if (ModelState.IsValid)
            {
                if (ConsumivelService.ConsumivelUnityOfWork.ConsumivelVeicularRepository.Editar(consumivelveicularModel))
                    return RedirectToAction(nameof(Index));
            }
            return View(consumivelveicularModel);
        }

        public IActionResult Details(int id) => View(ConsumivelService.ConsumivelUnityOfWork.ConsumivelVeicularRepository.ObterPorId(id));

        public IActionResult Delete(int id) => View(ConsumivelService.ConsumivelUnityOfWork.ConsumivelVeicularRepository.ObterPorId(id));

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            if (ConsumivelService.ConsumivelUnityOfWork.ConsumivelVeicularRepository.Remover(id))
                return RedirectToAction(nameof(Index));

            return View(ConsumivelService.ConsumivelUnityOfWork.ConsumivelVeicularRepository.ObterPorId(id));
        }

        public IActionResult Reports()
        {
            IEnumerable<ConsumivelVeicularModel> cns = ConsumivelService.ConsumivelUnityOfWork.ConsumivelVeicularRepository.ObterTodos();
            IEnumerable<RelatorioConsumivelVeicularViewModel> itens = cns.GroupBy(x => x.DataDespesa.Date).Select(y => new RelatorioConsumivelVeicularViewModel
            {
                Data = y.First().DataDespesa.ToString("dd/MM/yyyy"),
                Valor = y.Sum(z => z.Valor),
                ValorMasked = y.Sum(z => z.Valor) + " R$"
            });
            return View(itens);
        }
    }
}

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Views/ConsumivelVeicular/Create.cshtml
@model QueroTransporte.Model.ConsumivelVeicularModel

@{
    ViewData["Title"] = "Consumiveis";
}

<h2>Cadastro</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Placa Veiculo</label>
                @*ViewBag.RotaList is holding all the routs values*@
                @Html.DropDownListFor(model => model.IdVeiculo, ViewBag.Veiculos as SelectList, new
                { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdVeiculo, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataDespesa" class="control-label"></label>
                <input asp-for="DataDespesa" class="form-control" />
                <span asp-validation-for="DataDespesa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                <input asp-for="Categoria" class="form-control" />
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-success" />  <a class="btn btn-danger" asp-action="Index">Cancelar</a>

            </div>
        </form>
    </div>
</div>

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Views/ConsumivelVeicular/Delete.cshtml
@model QueroTransporte.Model.ConsumivelVeicularModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ConsumivelVeicularModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdVeiculo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdVeiculo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DataDespesa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DataDespesa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Categoria)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Remover" class="btn btn-success" />
        <a class="btn btn-danger" asp-action="Index">Cancelar</a>
    </form>
</div>

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Views/ConsumivelVeicular/Details.cshtml
@model QueroTransporte.Model.ConsumivelVeicularModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>ConsumivelVeicularModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdVeiculo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdVeiculo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DataDespesa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DataDespesa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Categoria)
        </dd>
    </dl>
</div>
<div>
    <a href="@Url.Action("Edit", "ConsumivelVeicular", new { id = Model.Id })" class="btn btn-info"><i class="fa fa-pencil"></i> Editar </a>
    <a class="btn btn-default" asp-action="Index">Voltar</a>
</div>

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Views/ConsumivelVeicular/Edit.cshtml
@model QueroTransporte.Model.ConsumivelVeicularModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ConsumivelVeicularModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdVeiculo" class="control-label"></label>
                <input asp-for="IdVeiculo" class="form-control" />
                <span asp-validation-for="IdVeiculo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataDespesa" class="control-label"></label>
                <input asp-for="DataDespesa" class="form-control" />
                <span asp-validation-for="DataDespesa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                <input asp-for="Categoria" class="form-control" />
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-success" />
                <a class="btn btn-danger" asp-action="Index">Cancelar</a>
            </div>
        </form>
    </div>
</div>

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Views/ConsumivelVeicular/Index.cshtml
@model IEnumerable<Domain.Models.ViewModel.ConsumivelVeiculoViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="x_title">
    <h2>Consumiveis Veiculares</h2>
    <a class="btn btn-primary" style="float:right" asp-controller="ConsumivelVeicular" asp-action="Create">Adicionar Consumivel</a>
    <div class="clearfix"></div>
</div>
<div class="x_content">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Veiculo.Placa)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ConsumivelVeicular.Valor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ConsumivelVeicular.DataDespesa)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ConsumivelVeicular.Categoria)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Veiculo.Placa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ConsumivelVeicular.Valor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ConsumivelVeicular.DataDespesa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ConsumivelVeicular.Categoria)
                    </td>
                    <td>
                        <a href="@Url.Action("Details", "ConsumivelVeicular", new { id = item.ConsumivelVeicular.Id })" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> Detalhes </a>
                        <a href="@Url.Action("Edit", "ConsumivelVeicular", new { id = item.ConsumivelVeicular.Id })" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Editar </a>
                        <a href="@Url.Action("Delete", "ConsumivelVeicular", new { id = item.ConsumivelVeicular.Id })" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Remover </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Views/ConsumivelVeicular/Reports.cshtml
@model IEnumerable<Model.ViewModel.RelatorioConsumivelVeicularViewModel>

@{
    ViewData["Title"] = "Reports";
}

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">

    google.charts.load('current', { 'packages': ['corechart'] });
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Data Despesa', 'Despesa total'],
            @foreach (var item in Model)
            {
                @:['@item.Data', @item.Valor],
            }
        ]);

        var options = {
            title: 'Gastos de consumíveis veículares',
            curveType: 'function',
            legend: { position: 'top', alignment: 'end' },
            hAxis: { minValue: 0, maxValue: 9 },
            curveType: 'function',
            pointSize: 20,
            vAxis: { scaleType: 'log' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

        chart.draw(data, options);
    }
</script>

<h2>Reports</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorMasked)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Data)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorMasked)
                </td>
            </tr>
        }

    </tbody>
</table>

<div id="curve_chart" style="width: 900px; height: 500px"></div>