Codigo/QueroTransporteSolucao/QueroTransporteWeb/Controllers/ComprarCreditosController.cs
using Domain.Interfaces.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Model.ViewModel;
using QueroTransporte.Model;
using QueroTransporteWeb.Resources.Methods;
using System;
using System.Collections.Generic;
using System.Security.Claims;

namespace QueroTransporteWeb.Controllers
{
    [Authorize]
    public class ComprarCreditosController : Controller
    {

        private readonly ICreditoService ComprarCreditoUnityOfWork;
        private readonly IUsuarioService UsuarioUnityOfWork;
        private readonly ITransacaoService TransacaoUnityOfWork;


        public ComprarCreditosController(IUsuarioService usuarioUnity,
                                         ICreditoService creditoUnity,
                                         ITransacaoService transacaoUnity)
        {
            ComprarCreditoUnityOfWork = creditoUnity;
            UsuarioUnityOfWork = usuarioUnity;
            TransacaoUnityOfWork = transacaoUnity;
        }

        /// <summary>
        /// Inicia a tela de comprar creditos
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            ViewBag.Creditos = addListaCreditos();
            return View();
        }

        /// <summary>
        /// Inicia a tela de comprar creditos e pega o objeto com dados da compra
        /// </summary>
        /// <param name="cv"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(CreditoViagemModel cv)
        {
            bool deferido;
            ViewBag.Creditos = addListaCreditos();
            cv.IdUsuario = MethodsUtils.RetornaUserLogado((ClaimsIdentity)User.Identity).Id;

            if (ModelState.IsValid)
            {
                if (UsuarioUnityOfWork.UsuarioUnityOfWork.UsuarioRepository.ObterPorId(cv.IdUsuario) != null)
                {
                    if (ComprarCreditoUnityOfWork.CreditoUnityOfWork.ComprarCreditoRepository.Inserir(cv))
                    {
                        TempData["mensagemSucesso"] = "Compra realizada com sucesso!.";
                        deferido = true;
                    }
                    else
                    {
                        TempData["mensagemErro"] = "Compra não pode ser realizada!.";
                        deferido = false;
                    }

                    if (!TransacaoUnityOfWork.TransacaoUnityOfWork.TransacaoRepository.Inserir(addTransacao(cv, deferido)))
                        TempData["mensagemErroTransacao"] = "Houve um problema ao gravar a transacao";
                }
                else
                    TempData["mensagemErro"] = "Compra não pode ser finalizada pois não existe nenhum usuário logado na sessão!.";

                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        private TransacaoModel addTransacao(CreditoViagemModel cv, bool deferido)
        {
            TransacaoModel tm = new TransacaoModel();
            tm.Data = DateTime.Now;
            tm.Deferido = deferido;
            tm.IdUsuario = cv.IdUsuario;
            tm.QtdCreditos = cv.Saldo;
            tm.Valor = cv.Saldo;
            if (deferido)
                tm.Status = "Aprovado";
            else
                tm.Status = "Cancelada";
            tm.Tipo = "COMPRA DE CREDITOS";

            return tm;
        }

        /// <summary>
        /// Metodo que adiciona valores de creditos para comprar(esses dados devem vir do banco)
        /// </summary>
        private List<CreditoViagemViewModel> addListaCreditos()
        {
            List<CreditoViagemViewModel> creditoViagem = new List<CreditoViagemViewModel>();

            creditoViagem.Add(new CreditoViagemViewModel(1, "5 Creditos Para Viagem", 5.00));
            creditoViagem.Add(new CreditoViagemViewModel(2, "10 Creditos Para Viagem", 10.00));
            creditoViagem.Add(new CreditoViagemViewModel(3, "15 Creditos Para Viagem", 15.00));

            return creditoViagem;
        }
    }
}

Codigo/QueroTransporteSolucao/QueroTransporteWeb/Views/ComprarCreditos/Index.cshtml
@model QueroTransporte.Model.CreditoViagemModel

@{
    ViewData["Title"] = "Comprar Créditos";
}



<div class="div-descricao">
    <h1>Comprar créditos</h1>
    <p>
        Compre seus créditos de viagem para pagar suas passagens!
    </p>
</div>

<div Class="div-carrinho">
    <div class="div-titulo">Carrinho</div>
    <div class="div-itens-carrinho" id="totalCreditos" value="0">Creditos 0</div>
    <div class="div-itens-carrinho" id="totalValor" value="0">Valor R$ 0</div>
</div>

<table class="table" style="margin-top: 1%">
    <tbody>
        @foreach (var item in (ViewBag.Creditos as IEnumerable<Model.ViewModel.CreditoViagemViewModel>))
        {
            <tr>
                <td>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(modelItem => item.Descricao)
                        </dt>
                        <dd>
                            @Html.DisplayFor(modelItem => item.Descricao)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(modelItem => item.Valor)
                        </dt>
                        <dd>
                            R$ @Html.DisplayFor(modelItem => item.Valor)
                        </dd>
                    </dl>
                </td>
                <td id="alinha-botoes">
                    <input id="btn-remove-credito" type="button" onclick="removeCredito(@Html.DisplayFor(modelItem => item.Valor))" value="Remover" class="btn btn-danger" />
                    <input id="btn-adiciona-credito" type="button" onclick="addCredito(@Html.DisplayFor(modelItem => item.Valor))" value="Adicionar" class="btn btn-primary" />
                </td>
            </tr>
        }
        <tr>
            <td>
                <dl class="dl-horizontal" id="add-outros-valores">
                    <dt>
                        Outros Valores
                    </dt>
                    <dd>
                        <input type="number" id="tentacles" name="tentacles"
                               min="15" max="100" class="form-control" value="0">
                    </dd>
                </dl>
            </td>
            <td>
                <div id="alinha-botoes2">
                    <input type="button" id="btn-remove-credito" onclick="removeCredito(parseInt($('#tentacles').val()))" value="Remover" class="btn btn-danger" />
                    <input type="button" id="btn-adiciona-credito" onclick="addCredito(parseInt($('#tentacles').val()))" value="Adicionar" class="btn btn-primary" />
                </div>
            </td>
        </tr>
    </tbody>
</table>

@if (TempData["mensagemErro"] != null)
{
    <div class="field-error" id="error-div">
        @TempData["mensagemErro"]
    </div>
}
else if (TempData["mensagemSucesso"] != null)
{
    <div class="success" id="sucess-div">
        @TempData["mensagemSucesso"]
    </div>
}

@if (TempData["mensagemErroTransacao"] != null)
{
    <div class="field-error" id="error-div">
        @TempData["mensagemErroTransacao"]
    </div>
}



<div id="btn-adiciona-credito">
    <div id="paypal-button-container"></div>
</div>


<div class="row" style="visibility: hidden">
    <div class="col-md-4">
        <form asp-action="Index" asp-controller="ComprarCreditos" name="form1">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" value="0" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Saldo" class="control-label"></label>
                <input asp-for="Saldo" id="saldo" class="form-control" value="0.0" />
                <span asp-validation-for="Saldo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdUsuario" class="control-label"></label>
                <input asp-for="IdUsuario" id="pessoa" class="form-control" value="1" />
                <span asp-validation-for="IdUsuario" class="text-danger"></span>
            </div>
        </form>
    </div>
</div>


<script src="https://www.paypal.com/sdk/js?client-id=sb&currency=BRL&merchant-id=CMY4AQXZEJFZA"></script>
<script>
    let qtdCreditos = 0;

    paypal.Buttons({
        createOrder: function (data, actions) {
            // Set up the transaction
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: qtdCreditos
                    }
                }]
            });
        },

        onApprove: function (data, actions) {
            // Capture the funds from the transaction
            return actions.order.capture().then(function (details) {
                // Show a success message to your buyer
                inputAutomatico();

                return fetch('/paypal-transaction-complete', {
                    method: 'post',
                    headers: {
                        'content-type': 'application/json'
                    },
                    body: JSON.stringify({
                        orderID: data.orderID
                    })
                });

            });

        }
    }).render('#paypal-button-container');

    function addCredito(value) {
        qtdCreditos += value;
        $(document).ready(function () {
            $("#totalCreditos").text('Creditos ' + qtdCreditos);
            $("#totalValor").text('Valor R$ ' + qtdCreditos);
            $('#saldo').value = qtdCreditos;

        });
    }

    function removeCredito(value) {
        if (qtdCreditos - value >= 0) {
            qtdCreditos = qtdCreditos - value;
        } else {
            qtdCreditos = 0;
        }

        $("#totalCreditos").text('Creditos ' + qtdCreditos);
        $("#totalValor").text('Valor R$ ' + qtdCreditos);
    }

    function inputAutomatico() {
        document.getElementById('saldo').value = parseFloat(qtdCreditos);
        document.forms["form1"].submit();
    }
</script>